import type { Metadata } from "next";
import { Geist, Geist_Mono, Hanuman } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hanuman = Hanuman({
  variable: "--font-hanuman",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.js Blogs Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hanuman.variable} antialiased`}
      >
        <Header />
        <main className="bg-gray-50">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
